modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${github}/issues"
license = "Unlicense"
logoFile = "omnilook.png"

[[mods]]
    modId = "omnilook"
    logoFile = "omnilook.png"
    version = "${version}"
    displayName = "${name}"
    authors = "rdh"
    description = "${description}"
