modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/rhysdh540/Omnilook/issues"
license = "Unlicense"
[[mods]]
modId = "omnilook"
version = "${version}"
displayName = "Omnilook"
authors = "rdh"
description = "funny look around mod"
[[dependencies.omnilook]]
modId = "forge"
mandatory = true
versionRange = "[37,49.999.999]"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.omnilook]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.20.4]"
ordering = "AFTER"
side = "CLIENT"
